version: '3.8'

services:
  aura-db:
    image: 270514764245.dkr.ecr.us-east-1.amazonaws.com/aura-postgres:latest
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.labels.mylabel == worker2
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: hrms
      PGDATA: /data
    networks:
      - aura-network
    volumes:
      - /home/backup:/data
    ports:
      - "5432:5432"

  aura-app:
    image: 270514764245.dkr.ecr.us-east-1.amazonaws.com/aura-app:latest
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.labels.mylabel == worker1
    networks:
      - aura-network
    ports:
      - "8080:8080"
    depends_on:
      - aura-db  # aura-app starts after aura-db

  aura-frontend:
    image: 270514764245.dkr.ecr.us-east-1.amazonaws.com/aura-frontend:latest
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.labels.mylabel == worker1
    networks:
      - aura-network
    ports:
      - "80:80"
    depends_on:
      - aura-app  # aura-frontend starts after aura-app

networks:
  aura-network:
    driver: overlay
