version: '3.8'

services:
  aura-db:
    image: 270514764245.dkr.ecr.us-east-1.amazonaws.com/aura-postgres:${AURA_DB_TAG}
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.labels.mylabel == worker2
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: hrms
      PGDATA: /data
    networks:
      - aura-network
    volumes:
      - /home/backup:/data
    ports:
      - "5432:5432"

  aura-app:
    image: 270514764245.dkr.ecr.us-east-1.amazonaws.com/aura-app:${AURA_APP_TAG}
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.labels.mylabel == worker1
    environment:
      AWS_ACCESS_KEY_ID: "AKIAT567PXHK6WVKNEOS3"
      AWS_SECRET_ACCESS_KEY: "9yZfLNgfLmMtIc+uERbDFw+jygll+MtjuX8rqWZKl"
      OTP_API_KEY: "5d7dbdd8-6498-11ef-8b60-0200cd936042"
      AWS_REGION: "ap-south-1"
    networks:
      - aura-network
    ports:
      - "8080:8080"
    depends_on:
      - aura-db  # aura-app starts after aura-db
    dns:
      - 8.8.8.8 
      - 8.8.4.4  

  aura-frontend:
    image: 270514764245.dkr.ecr.us-east-1.amazonaws.com/aura-frontend:${AURA_FRONTEND_TAG}
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.labels.mylabel == worker1
    networks:
      - aura-network
    ports:
      - "80:80"
    depends_on:
      - aura-app  # aura-frontend starts after aura-app

networks:
  aura-network:
    driver: overlay
